from http.server import BaseHTTPRequestHandler
import json
import sys
from io import BytesIO

class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        try:
            # Read request body
            content_length = int(self.headers.get('Content-Length', 0))
            if content_length > 0:
                post_data = self.rfile.read(content_length)
                try:
                    request_data = json.loads(post_data.decode('utf-8'))
                except json.JSONDecodeError:
                    request_data = {}
            else:
                request_data = {}
            
            print(f"Received request: {request_data}", file=sys.stderr)
            
            # Try to generate a simple PDF using reportlab
            try:
                from reportlab.pdfgen import canvas
                from reportlab.lib.pagesizes import letter
                
                # Create PDF in memory
                buffer = BytesIO()
                c = canvas.Canvas(buffer, pagesize=letter)
                
                # Add title from request
                title = request_data.get('title', 'Test Document')
                c.drawString(100, 750, f"Title: {title}")
                
                # Add authors
                authors = request_data.get('authors', [])
                if authors:
                    author_names = [author.get('name', 'Unknown') for author in authors]
                    c.drawString(100, 730, f"Authors: {', '.join(author_names)}")
                
                c.drawString(100, 700, "This PDF was generated by Python serverless function!")
                c.save()
                
                pdf_data = buffer.getvalue()
                buffer.close()
                
                print(f"Generated PDF: {len(pdf_data)} bytes", file=sys.stderr)
                
                # Return PDF
                self.send_response(200)
                self.send_header('Content-Type', 'application/pdf')
                self.send_header('Content-Length', str(len(pdf_data)))
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(pdf_data)
                
            except Exception as pdf_error:
                print(f"PDF generation error: {str(pdf_error)}", file=sys.stderr)
                # Return JSON error
                error_response = {
                    'success': False,
                    'error': f'PDF generation failed: {str(pdf_error)}',
                    'request_data': request_data
                }
                
                self.send_response(500)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(json.dumps(error_response).encode())
                
        except Exception as e:
            print(f"Handler error: {str(e)}", file=sys.stderr)
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            error_response = {'success': False, 'error': str(e)}
            self.wfile.write(json.dumps(error_response).encode())
    
    def do_GET(self):
        # For testing
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        response = {'success': True, 'message': 'PDF generator is ready'}
        self.wfile.write(json.dumps(response).encode())
    
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()